PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX af: <http://purl.org/ontology/af/>

SELECT ?signal ?dimension ?vectors
WHERE
{
        <http://KSA_CHARM_306> a mo:Signal;
        af:dimension ?dimension;
        af:vectors ?vectors.
}

